### ISSUE TITLE
Server won't launch after last update

### ISSUE THREAD

**Issue by ghost** [klikli-dev/modonomicon#177]
**Describe the bug**
```
[main/WARN] [minecraft/Main]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void com.klikli_dev.modonomicon.book.page.BookRecipePage.<init>(net.minecraft.world.item.crafting.RecipeType, com.klikli_dev.modonomicon.book.BookTextHolder, net.minecraft.resources.ResourceLocation, com.klikli_dev.modonomicon.book.BookTextHolder, net.minecraft.resources.ResourceLocation, com.klikli_dev.modonomicon.book.BookTextHolder, java.lang.String)'
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?] {re:mixin}
        at net.minecraft.server.Main.main(Main.java:195) ~[server-1.20.1-20230612.114412-srg.jar%231043!/:?] {re:mixin,re:classloading,pl:mixin:A}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.serverService(CommonLaunchHandler.java:103) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lambda$makeService$0(CommonServerLaunchHandler.java:27) ~[fmlloader-1.20.1-47.2.20.jar%2369!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar%2355!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}
Caused by: java.lang.NoSuchMethodError: 'void com.klikli_dev.modonomicon.book.page.BookRecipePage.<init>(net.minecraft.world.item.crafting.RecipeType, com.klikli_dev.modonomicon.book.BookTextHolder, net.minecraft.resources.ResourceLocation, com.klikli_dev.modonomicon.book.BookTextHolder, net.minecraft.resources.ResourceLocation, com.klikli_dev.modonomicon.book.BookTextHolder, java.lang.String)'
        at com.klikli_dev.occultism.integration.modonomicon.pages.BookRitualRecipePage.<init>(BookRitualRecipePage.java:23) ~[occultism-1.20.1-1.116.2.jar%23892!/:1.116.2] {re:classloading}
        at com.klikli_dev.occultism.integration.modonomicon.pages.BookRitualRecipePage.fromJson(BookRitualRecipePage.java:29) ~[occultism-1.20.1-1.116.2.jar%23892!/:1.116.2] {re:classloading}
        at com.klikli_dev.modonomicon.book.BookEntry.fromJson(BookEntry.java:121) ~[modonomicon-1.20.1-forge-1.60.0.jar%23860!/:1.54.4] {re:classloading}
        at com.klikli_dev.modonomicon.data.BookDataManager.loadEntry(BookDataManager.java:202) ~[modonomicon-1.20.1-forge-1.60.0.jar%23860!/:1.54.4] {re:classloading}
        at com.klikli_dev.modonomicon.data.BookDataManager.apply(BookDataManager.java:301) ~[modonomicon-1.20.1-forge-1.60.0.jar%23860!/:1.54.4] {re:classloading}
        at com.klikli_dev.modonomicon.data.BookDataManager.m_5787_(BookDataManager.java:46) ~[modonomicon-1.20.1-forge-1.60.0.jar%23860!/:1.54.4] {re:classloading}
        at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[server-1.20.1-20230612.114412-srg.jar%231043!/:?] {re:mixin,re:computing_frames,re:classloading,pl:mixin:APP:moonlight.mixins.json:ConditionHackMixin,pl:mixin:A}
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?] {}
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
        at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[server-1.20.1-20230612.114412-srg.jar%231043!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.Util.m_214652_(Util.java:783) ~[server-1.20.1-20230612.114412-srg.jar%231043!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.UtilMixin,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:A}
        at net.minecraft.Util.m_214679_(Util.java:772) ~[server-1.20.1-20230612.114412-srg.jar%231043!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:UtilMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_priorities.UtilMixin,pl:mixin:APP:ftbchunks-common.mixins.json:UtilMixin,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin,pl:mixin:APP:bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:A}
        at net.minecraft.server.Main.main(Main.java:166) ~[server-1.20.1-20230612.114412-srg.jar%231043!/:?] {re:mixin,re:classloading,pl:mixin:A}
        ... 15 more
```

**To Reproduce**
1.Update to 1.20.1-forge-1.60.0
2. launch server
3. error

**Expected behavior**
normal server load... the error goes away when i downgrade to the version before.

**System (please complete the following information):**
- Modonomicon Version: 1.20.1-forge-1.60.0
- OS: [e.g. Windows] win 11
- Minecraft Version: 1.20.1
- Modpack Link and Version, or list of mods: https://legacy.curseforge.com/minecraft/modpacks/the-next-chapter/

**Comment by Mysticpasta1** [comment]
this also happens when creating a new world too!

**Comment by klikli-dev** [comment]
Oh ouch - need to update occultism and theurgy.
Overlooked that because the change in question was made by a community member. Will do ASAP.
For now rolling back one version should allow you to start :)

**Comment by klikli-dev** [comment]
Addressed in:
https://github.com/klikli-dev/theurgy/commit/52dff5ee17ddb861b13b4c44ac075eaeedabf264
https://github.com/klikli-dev/theurgy/commit/67c7192d0667da529fa3c750a774d3fd068ed766
https://github.com/klikli-dev/occultism/commit/e2f8257a6da27ede65fbde672adc5b74fd6ed88e
https://github.com/klikli-dev/occultism/commit/56de82167fee1d07f74713d39df041dd1bb4e7a7
