### ISSUE TITLE
Crash when clicking on item in book

### ISSUE THREAD

**Issue by DaFuqs** [klikli-dev/modonomicon#275]
Original issue: https://github.com/DaFuqs/Spectrum/issues/650
Reposting it here since when looking at the crashlog it's a `ModonomiconJeiIntegration` issue.

**Describe the bug**
Clicking on a vanilla item with EMI+JEI installed will crash the game.

```
Description: mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "mezz.jei.api.runtime.IJeiRuntime.getJeiHelpers()" because "com.klikli_dev.modonomicon.integration.ModonomiconJeiIntegration$ModonomiconJeiPlugin.jeiRuntime" is null
	at knot//com.klikli_dev.modonomicon.integration.ModonomiconJeiIntegration$ModonomiconJeiHelper.showRecipe(ModonomiconJeiIntegration.java:60)
	at knot//com.klikli_dev.modonomicon.integration.ModonomiconJeiIntegration.showRecipe(ModonomiconJeiIntegration.java:44)
	at knot//com.klikli_dev.modonomicon.client.gui.book.BookContentScreen.method_25430(BookContentScreen.java:726)
	at knot//com.klikli_dev.modonomicon.client.gui.book.BookContentScreen.method_25402(BookContentScreen.java:793)
	at knot//net.minecraft.class_312.method_1611(class_312.java:98)
	at knot//net.minecraft.class_437.method_25412(class_437.java:409)
	at knot//net.minecraft.class_312.method_1601(class_312.java:98)
	at knot//net.minecraft.class_312.method_22686(class_312.java:169)
	at knot//net.minecraft.class_1255.execute(class_1255.java:102)
	at knot//net.minecraft.class_312.method_22684(class_312.java:169)
	at knot//org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
	at knot//org.lwjgl.system.JNI.invokeV(Native Method)
	at knot//org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at knot//com.mojang.blaze3d.systems.RenderSystem.pollEvents(RenderSystem.java:201)
	at knot//com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:219)
	at knot//net.minecraft.class_1041.method_15998(class_1041.java:288)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1241)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**To Reproduce**
Open the Colorful World book, find an entry where a vanilla item is mentioned (for example: mud dipping four-leaf clover into a scute) and click the said item (in this case, the highlighted text mentioning the scute).

**Expected behavior**
Not a crash, obviously.

**System (please complete the following information):**
- Modloader: Fabric
- Modonomicon Version: 1.77.3
- Minecraft Version: 1.20.1

**Additional context**
[Crash Log](https://github.com/user-attachments/files/18275103/crash-2024-12-30_03.24.17-client.txt)

**Comment by klikli-dev** [comment]
Thanks for reporting! 

Out of interest, does it NOT crash if a modded item is clicked??

**Comment by DaFuqs** [comment]
I have not tested it myself, but I assume the player that reported it just wanted to point at that is even happens for "non modded" items, so I assume all items will crash 😄

If you want to I can test it out tomorrow
